version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: norionomura/swift:swift-4.1-branch
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
          POSTGRES_PASSWORD: vapor_password
    steps:
      - run:
          name: Update APT
          command: apt-get update
      - run:
          name: Install Swift NIO dependencies
          command: apt-get install -yq pkg-config libssl-dev
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release


workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - linux
      # - macos
      