version: 2

jobs:
  macos:
    macos:
      xcode: "9.2"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: codevapor/swift:4.1
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: vapor_username
          POSTGRES_DB: vapor_database
    steps:
      - checkout
      - run: 
          name: Compile code
          command: swift build
      - run: 
          name: Run unit tests
          command: swift test
      - run: 
          name: Compile code with optimizations
          command: swift build -c release


workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos

  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                
    jobs:
      - linux
      # - macos
      