version: '3'

services:
  test:
    build: 
      context: .
      dockerfile: test.Dockerfile
    depends_on: 
      - psql-10
  psql-11:
    image: postgres:11
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_DB: vapor_database
      POSTGRES_PASSWORD: vapor_password
    ports:
      - 5432:5432
  psql-10:
    image: postgres:10
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_DB: vapor_database
      POSTGRES_PASSWORD: vapor_password
    ports:
      - 5432:5432
  psql-9:
    image: postgres:9
    environment:
      POSTGRES_USER: vapor_username
      POSTGRES_DB: vapor_database
      POSTGRES_PASSWORD: vapor_password
    ports:
      - 5432:5432

